cesar.shimura@gmail.com  
January 2023 - Source: HLTV

# Introduction

Collect data from HLTV from Imperial CSGO team and retrieve insights on team's performance, mainly focus on last year which FalleN created the "Last Dance" project.

In [1]:
# Importing libraries

import requests
import bs4
import numpy as np
import pandas as pd

In [2]:
# Getting access to Imperial page on HTLV

res = requests.get("https://www.hltv.org/results?team=9455")
soup = bs4.BeautifulSoup(res.text,'lxml')

In [3]:
# Adding a 1st filter to work with only interested part of the website

raw_data = soup.find_all('div', attrs={'results-sublist'})

First, for each match, we are interested on retrieving what teams were playing, their final score, what date, tournment and map or result from best of 3 matches (bo3).
Some matches are best of 1, which there is a single map played, or best of 3 (bo3), which it consists of maximum 3 maps.

In [4]:
# Creating lists to store retrieved data

team_1 = [] # First team that appear on the left side of the website (only Imperial, since it is the team's page)
team_2 = [] # Second team that appear on the right side of the website
score = [] # Score of the match (bo1 or bo3)
date = [] # Date
champ = [] # Name of the tournament
map_md3 = [] # Map or signalled bo3 (best of 3)
ref = [] # Select webpage reference

In [5]:
# Getting team_1 and team_2

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        team_1.append(row.find_all('td', {'team-cell'})[0].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[1].find('img').get('title'))
    elif len(row.find_all('td', {'team-cell'})) == 4:
        team_1.append(row.find_all('td', {'team-cell'})[0].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[1].find('img').get('title'))
        team_1.append(row.find_all('td', {'team-cell'})[2].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[3].find('img').get('title'))
    elif len(row.find_all('td', {'team-cell'})) == 6:
        team_1.append(row.find_all('td', {'team-cell'})[0].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[1].find('img').get('title'))
        team_1.append(row.find_all('td', {'team-cell'})[2].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[3].find('img').get('title'))
        team_1.append(row.find_all('td', {'team-cell'})[4].find('img').get('title'))
        team_2.append(row.find_all('td', {'team-cell'})[5].find('img').get('title'))
    else:
        pass

In [6]:
# Getting score

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        score.append(row.find_all('td',{'result-score'})[0].text)
    elif len(row.find_all('td', {'team-cell'})) == 4:
        score.append(row.find_all('td',{'result-score'})[0].text)
        score.append(row.find_all('td',{'result-score'})[1].text)
    elif len(row.find_all('td', {'team-cell'})) == 6:
        score.append(row.find_all('td',{'result-score'})[0].text)
        score.append(row.find_all('td',{'result-score'})[1].text)
        score.append(row.find_all('td',{'result-score'})[2].text)
    else:
        pass

In [7]:
# Getting Date

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        date.append(row.find('span', {'standard-headline'}).text)
    elif len(row.find_all('td', {'team-cell'})) == 4:
        date.append(row.find('span', {'standard-headline'}).text)
        date.append(row.find('span', {'standard-headline'}).text)
    elif len(row.find_all('td', {'team-cell'})) == 6:
        date.append(row.find('span', {'standard-headline'}).text)
        date.append(row.find('span', {'standard-headline'}).text)
        date.append(row.find('span', {'standard-headline'}).text)
    else:
        pass

In [8]:
# Getting tournment

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        champ.append(row.find_all('td', {'event'})[0].find('img').get('alt'))
    elif len(row.find_all('td', {'team-cell'})) == 4:
        champ.append(row.find_all('td', {'event'})[0].find('img').get('alt'))
        champ.append(row.find_all('td', {'event'})[1].find('img').get('alt'))
    elif len(row.find_all('td', {'team-cell'})) == 6:
        champ.append(row.find_all('td', {'event'})[0].find('img').get('alt'))
        champ.append(row.find_all('td', {'event'})[1].find('img').get('alt'))
        champ.append(row.find_all('td', {'event'})[2].find('img').get('alt'))
    else:
        pass

In [9]:
# Get map or bo3 (best of 3 - consists of three maps)

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        map_md3.append(row.find_all('div', {'map-text'})[0].text)
    elif len(row.find_all('td', {'team-cell'})) == 4:
        map_md3.append(row.find_all('div', {'map-text'})[0].text)
        map_md3.append(row.find_all('div', {'map-text'})[1].text)
    elif len(row.find_all('td', {'team-cell'})) == 6:
        map_md3.append(row.find_all('div', {'map-text'})[0].text)
        map_md3.append(row.find_all('div', {'map-text'})[1].text)
        map_md3.append(row.find_all('div', {'map-text'})[2].text)
    else:
        pass

In [10]:
# Get webpage reference of the match

for row in raw_data:
    if len(row.find_all('td', {'team-cell'})) == 2:
        ref.append(row.find_all('div',{'result-con'})[0].find('a').get('href'))
    elif len(row.find_all('td', {'team-cell'})) == 4:
        ref.append(row.find_all('div',{'result-con'})[0].find('a').get('href'))
        ref.append(row.find_all('div',{'result-con'})[1].find('a').get('href'))
    elif len(row.find_all('td', {'team-cell'})) == 6:
        ref.append(row.find_all('div',{'result-con'})[0].find('a').get('href'))
        ref.append(row.find_all('div',{'result-con'})[1].find('a').get('href'))
        ref.append(row.find_all('div',{'result-con'})[2].find('a').get('href'))
    else:
        pass

In [11]:
# Aggregagting lists to visualize in pandas

d = {'team_1':team_1,
    'team_2':team_2,
    'score': score,
    'date': date,
    'championship': champ,
    'map': map_md3,
    'ref': ref}

In [12]:
# Creating a Dataframe

df = pd.DataFrame(d)

### Dataframe A: df

In [13]:
df.head()

,team_1,team_2,score,date,championship,map,ref
0,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...
1,Imperial,RED Canids,16 - 8,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,nuke,/matches/2361439/imperial-vs-red-canids-iem-br...
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...
3,Imperial,Cloud9,0 - 2,Results for November 2nd 2022,IEM Rio Major 2022 Challengers Stage,bo3,/matches/2359796/cloud9-vs-imperial-iem-rio-ma...
4,Imperial,9z,11 - 16,Results for November 1st 2022,IEM Rio Major 2022 Challengers Stage,mrg,/matches/2359786/9z-vs-imperial-iem-rio-major-...

In [14]:
len(df)

100

**Observations**

* We can see that the len of the df is 100 entries (maximum allowed per page).
* Some values from the map column appear bo3, which impacts on the score. We need to further analyze the matches played in each bo3.
* Imperial team always appears at first as team 1. This help us understand the score column, wheter Imperial won or not the match.

Since some maps were played bo3 format and we are interested in each map outcome, I'll first separate the main df into 2  dataframes to better work with the df that needs further data gathering.

In [15]:
# Checking for unique values in the map column

df['map'].unique()

array(['vtg', 'nuke', 'bo3', 'mrg', 'inf', 'ovp', 'd2', 'anc'],
      dtype=object)

In [16]:
# I'm removing bo5 to facilitate data retrieving

df.drop(df[df['map'] == 'bo5'].index, inplace = True)

In [17]:
# Filtering those maps from bo3

single_map = ['mrg', 'inf', 'nuke', 'd2', 'vtg', 'anc', 'ovp']

bo3 = ['bo3']

In [18]:
# Creating two separate df based on single map and bo3

df_bo3 = df[df['map'].isin(bo3)]
df_smap = df[df['map'].isin(single_map)]

### Dataframe B: df_bo3

In [19]:
df_bo3.head()

,team_1,team_2,score,date,championship,map,ref
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...
3,Imperial,Cloud9,0 - 2,Results for November 2nd 2022,IEM Rio Major 2022 Challengers Stage,bo3,/matches/2359796/cloud9-vs-imperial-iem-rio-ma...
6,Imperial,paiN,1 - 2,Results for October 16th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359558/pain-vs-imperial-flow-firelea...
7,Imperial,Isurus,2 - 0,Results for October 15th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359377/imperial-vs-isurus-flow-firel...
8,Imperial,Complexity,2 - 1,Results for October 10th 2022,IEM Road to Rio 2022 Americas RMR,bo3,/matches/2358384/complexity-vs-imperial-iem-ro...

In [20]:
len(df_bo3)

56

### Dataframe C: df_smap

In [21]:
df_smap.head()

,team_1,team_2,score,date,championship,map,ref
0,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...
1,Imperial,RED Canids,16 - 8,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,nuke,/matches/2361439/imperial-vs-red-canids-iem-br...
4,Imperial,9z,11 - 16,Results for November 1st 2022,IEM Rio Major 2022 Challengers Stage,mrg,/matches/2359786/9z-vs-imperial-iem-rio-major-...
5,Imperial,Vitality,9 - 16,Results for October 31st 2022,IEM Rio Major 2022 Challengers Stage,inf,/matches/2359614/vitality-vs-imperial-iem-rio-...
12,Imperial,00NATION,11 - 16,Results for October 6th 2022,IEM Road to Rio 2022 Americas RMR,inf,/matches/2358367/imperial-vs-00nation-iem-road...

In [22]:
len(df_smap)

44

## Best of 3 (bo3) - Maps Results

In [23]:
# Creating function to calculate how many maps were played in each bo3 match.

def split_score(str):
    return [int(str.split(' - ')[0]),int(str.split(' - ')[1])]

In [24]:
# Adding column that sum the number of maps played in each bo3 match.

df_bo3['total_matches'] = df['score'].apply(lambda x:sum(split_score(x)))

C:\Users\cesar\AppData\Local\Temp\ipykernel_29736\11217786.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bo3['total_matches'] = df['score'].apply(lambda x:sum(split_score(x)))

In [25]:
# Checking new column

df_bo3.head()

,team_1,team_2,score,date,championship,map,ref,total_matches
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2
3,Imperial,Cloud9,0 - 2,Results for November 2nd 2022,IEM Rio Major 2022 Challengers Stage,bo3,/matches/2359796/cloud9-vs-imperial-iem-rio-ma...,2
6,Imperial,paiN,1 - 2,Results for October 16th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359558/pain-vs-imperial-flow-firelea...,3
7,Imperial,Isurus,2 - 0,Results for October 15th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359377/imperial-vs-isurus-flow-firel...,2
8,Imperial,Complexity,2 - 1,Results for October 10th 2022,IEM Road to Rio 2022 Americas RMR,bo3,/matches/2358384/complexity-vs-imperial-iem-ro...,3

In [26]:
# Creating new variables to retrieve bo3 matches

team_1_page = []
team_2_page = []
score_1 = []
score_2 = []
map_bo3 = []
champ = []

In [27]:
# Since I want to maintain the same index order to use later, I'll repeat it 3x each value

indexes = np.repeat(list(df_bo3['ref'].index),3)

In [28]:
# Getting teams, score, map and name of the tournament

main_site = 'https://www.hltv.org/'

for ref in df_bo3['ref']:
    main_page = main_site + ref
    res_page = requests.get(main_page)
    soup_page = bs4.BeautifulSoup(res_page.text,'lxml')
    
    team_1_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[0].find('img').get('alt'))
    team_1_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[2].find('img').get('alt'))
    team_1_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[4].find('img').get('alt'))
    
    team_2_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[1].find('img').get('alt'))
    team_2_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[3].find('img').get('alt'))
    team_2_page.append(soup_page.find_all('div',{'results-teamlogo-container'})[5].find('img').get('alt'))
    
    score_1.append(soup_page.find_all('div',{'results-team-score'})[0].text)
    score_1.append(soup_page.find_all('div',{'results-team-score'})[2].text)
    score_1.append(soup_page.find_all('div',{'results-team-score'})[4].text)
    
    score_2.append(soup_page.find_all('div',{'results-team-score'})[1].text)
    score_2.append(soup_page.find_all('div',{'results-team-score'})[3].text)
    score_2.append(soup_page.find_all('div',{'results-team-score'})[5].text)
    
    map_bo3.append(soup_page.find_all('div', {'map-name-holder'})[0].find('img').get('alt'))
    map_bo3.append(soup_page.find_all('div', {'map-name-holder'})[1].find('img').get('alt'))
    map_bo3.append(soup_page.find_all('div', {'map-name-holder'})[2].find('img').get('alt'))
    
    champ.append(soup_page.find_all('div', {'event text-ellipsis'})[0].find('a').get('title'))
    champ.append(soup_page.find_all('div', {'event text-ellipsis'})[0].find('a').get('title'))
    champ.append(soup_page.find_all('div', {'event text-ellipsis'})[0].find('a').get('title'))

In [29]:
# Putting together into a DataFrame

d_page = {'team_1': team_1_page,
          'team_2': team_2_page,
          'score_1': score_1,
          'score_2': score_2,
          'map': map_bo3,
          'championship': champ,
         'indexes':indexes}

df_bo3_maps = pd.DataFrame(d_page)

### Sub Dataframe B.1: df_bo3_sub

In [30]:
df_bo3_maps.head()

,team_1,team_2,score_1,score_2,map,championship,indexes
0,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2
1,Imperial,00NATION,16,10,Overpass,ESL Pro League Season 17 Conference South America,2
2,Imperial,00NATION,-,-,Ancient,ESL Pro League Season 17 Conference South America,2
3,Cloud9,Imperial,19,15,Overpass,IEM Rio Major 2022 Challengers Stage,3
4,Cloud9,Imperial,22,19,Vertigo,IEM Rio Major 2022 Challengers Stage,3

In [31]:
len(df_bo3_maps)

168

## Best of 3 (bo3) - Players Performance

In each map result, I'm creating two functions that retrieve each players kd (kill-death) result. Each function is used depending the number of maps played.

In [32]:
# Creating variables to store new kd dataset

players_t1 = []
players_t2 = []
kd_t1 = []
kd_t2 = []

In [33]:
# Creating a function to retrieve kd of each player for two maps played

def m2_players_kd(ref):
    
    main_page = main_site + ref
    res_page = requests.get(main_page)
    soup_page = bs4.BeautifulSoup(res_page.text,'lxml')

    # 1st map

    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[31].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[32].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[33].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[34].find('span', {'player-nick'}).text)

    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[38].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[39].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[40].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[41].text)

    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+16].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+17].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+18].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+19].find('span', {'player-nick'}).text)

    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+19].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+20].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+21].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+22].text)

    # 2nd map

    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+16].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+17].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+18].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+19].find('span', {'player-nick'}).text)

    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+19].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+20].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+21].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+22].text)

    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+16].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+17].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+18].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+19].find('span', {'player-nick'}).text)

    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+19].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+20].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+21].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+22].text)

In [34]:
# Creating a function to retrieve kd of each player for three maps played

def m3_players_kd(ref):
    
    main_page = main_site + ref
    res_page = requests.get(main_page)
    soup_page = bs4.BeautifulSoup(res_page.text,'lxml')

    # 1st map

    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[31].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[32].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[33].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[34].find('span', {'player-nick'}).text)

    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[38].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[39].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[40].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[41].text)

    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+16].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+17].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+18].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+19].find('span', {'player-nick'}).text)

    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+19].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+20].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+21].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+22].text)

    # 2nd map

    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+16].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+17].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+18].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+19].find('span', {'player-nick'}).text)

    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+19].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+20].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+21].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+22].text)

    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+16].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+17].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+18].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+19].find('span', {'player-nick'}).text)

    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+19].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+20].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+21].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+22].text)
    
    # 3rd map
    
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+16].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+17].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+18].find('span', {'player-nick'}).text)
    players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+19].find('span', {'player-nick'}).text)

    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+19].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+20].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+21].text)
    kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+22].text)

    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15+15].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15+16].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15+17].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15+18].find('span', {'player-nick'}).text)
    players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15+15+15+15+19].find('span', {'player-nick'}).text)

    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18+18].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18+19].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18+20].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18+21].text)
    kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18+18+18+18+22].text)

In [35]:
# Retrieving players performance depending the numbers of maps played

for i in np.arange(len(df_bo3['total_matches'])):
    if df_bo3['total_matches'].iloc[i] == 2:
        m2_players_kd(df_bo3['ref'].iloc[i])
    elif df_bo3['total_matches'].iloc[i] == 3:
        m3_players_kd(df_bo3['ref'].iloc[i])
    else:
        pass

In [36]:
# Putting together into a DataFrame

d_kd = {'players_t1': players_t1,
        'kd_t1': kd_t1,
        'players_t2': players_t2,
        'kd_t2': kd_t2}

df_bo3_players = pd.DataFrame(d_kd)

### Sub Dataframe B.2: df_bo3_players

In [37]:
df_bo3_players.head()

  players_t1  kd_t1 players_t2  kd_t2
0      chelo  25-12      dumau   8-16
1       VINI   21-8        nqz  10-15
2     FalleN   13-5   coldzera  11-19
3       JOTA   13-9       TACO   8-18
4      boltz   12-9      latto   6-17

In [38]:
len(df_bo3_players)

670

## Best of 3 (bo3) - Adding Together Maps Results (B.1) and Player Performance (B.2)

In [39]:
# Creating a copy of Maps Results dataframe

#df_bo3_sub_c = df_bo3_maps.copy()

In [40]:
# Cleaning the Maps Results dataframe: removing rows (maps) that supposed to be played, but it ended before (2-0 or 0-2)
# Hence, that map wasn't played it.

df_bo3_maps.drop(df_bo3_maps[df_bo3_maps['score_1'] == '-'].index, inplace = True)

In [41]:
# Reseting index of both dataframes

df_bo3_maps.reset_index(drop=True, inplace = True)
df_bo3_players.reset_index(drop=True,inplace=True)

In [42]:
# Creating a DataFrame draft with the final columns that I want in the final df

df_bo3_subfinal = pd.DataFrame(columns = ['team_1', 'team_2', 'score_1', 'score_2', 'map', 'championship','indexes', 'players_t1', 'kd_t1', 'players_t2', 'kd_t2'])

In [43]:
# Final columns for bo3 dataframe

df_bo3_subfinal

Empty DataFrame
Columns: [team_1, team_2, score_1, score_2, map, championship, indexes, players_t1, kd_t1, players_t2, kd_t2]
Index: []

In [44]:
# Merging Maps Results and Player Performance into a single DataFrame

i = 0
j = 0


for i in np.arange(len(df_bo3_maps)):
    sub_df_1 = df_bo3_maps.iloc[[i]].reset_index(drop=True)
    
    j = i*5
    
    sub_df_2 = df_bo3_players.iloc[j:j+5].reset_index(drop=True)
    
    concat = pd.concat([sub_df_1, sub_df_2], axis = 1).fillna(method="ffill", axis=0)
    
    df_bo3_subfinal = pd.concat([df_bo3_subfinal, concat], axis = 0)

### Dataframe B.3: df_bo3_subfinal

In [45]:
df_bo3_subfinal.head()

,team_1,team_2,score_1,score_2,map,championship,indexes,players_t1,kd_t1,players_t2,kd_t2
0,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2.0,chelo,25-12,dumau,8-16
1,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2.0,VINI,21-8,nqz,10-15
2,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2.0,FalleN,13-5,coldzera,11-19
3,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2.0,JOTA,13-9,TACO,8-18
4,Imperial,00NATION,16,3,Nuke,ESL Pro League Season 17 Conference South America,2.0,boltz,12-9,latto,6-17

### Adding Maps Results and Players Performance (B.3) into the main Dataframe Bo3 (B)

In [46]:
# Main df

df_bo3.head()

,team_1,team_2,score,date,championship,map,ref,total_matches
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2
3,Imperial,Cloud9,0 - 2,Results for November 2nd 2022,IEM Rio Major 2022 Challengers Stage,bo3,/matches/2359796/cloud9-vs-imperial-iem-rio-ma...,2
6,Imperial,paiN,1 - 2,Results for October 16th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359558/pain-vs-imperial-flow-firelea...,3
7,Imperial,Isurus,2 - 0,Results for October 15th 2022,Flow FiReLEAGUE 2022 Global Finals,bo3,/matches/2359377/imperial-vs-isurus-flow-firel...,2
8,Imperial,Complexity,2 - 1,Results for October 10th 2022,IEM Road to Rio 2022 Americas RMR,bo3,/matches/2358384/complexity-vs-imperial-iem-ro...,3

In [47]:
# Reseting index

df_bo3_players.reset_index(drop=True, inplace = True)

In [48]:
# Removing columns from df_bo3_players

df_bo3_subfinal_c = df_bo3_subfinal.drop(['team_1', 'team_2','championship'], axis = 1)

In [49]:
# Merge both datraframes based on index

df_bo3_f = pd.merge(df_bo3,df_bo3_subfinal_c,how = 'left',left_index = True, right_on = 'indexes')

### Dataframe B.Final:

In [50]:
df_bo3_f.head(10)

,team_1,team_2,score,date,championship,map_x,ref,total_matches,score_1,score_2,map_y,indexes,players_t1,kd_t1,players_t2,kd_t2
0,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,chelo,25-12,dumau,8-16
1,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,VINI,21-8,nqz,10-15
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,FalleN,13-5,coldzera,11-19
3,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,JOTA,13-9,TACO,8-18
4,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,boltz,12-9,latto,6-17
0,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,10,Overpass,2.0,FalleN,24-12,dumau,19-19
1,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,10,Overpass,2.0,VINI,16-15,coldzera,16-19
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,10,Overpass,2.0,chelo,20-16,latto,11-19
3,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,10,Overpass,2.0,JOTA,17-14,nqz,17-20
4,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,10,Overpass,2.0,boltz,18-17,TACO,11-18

## Single Map Played - Players Performance

For maps that were played once, we don't need to get data about Maps Results, only Players Performance

In [51]:
# Checking once again Dataframe C of only single map played

df_smap.head()

,team_1,team_2,score,date,championship,map,ref
0,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...
1,Imperial,RED Canids,16 - 8,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,nuke,/matches/2361439/imperial-vs-red-canids-iem-br...
4,Imperial,9z,11 - 16,Results for November 1st 2022,IEM Rio Major 2022 Challengers Stage,mrg,/matches/2359786/9z-vs-imperial-iem-rio-major-...
5,Imperial,Vitality,9 - 16,Results for October 31st 2022,IEM Rio Major 2022 Challengers Stage,inf,/matches/2359614/vitality-vs-imperial-iem-rio-...
12,Imperial,00NATION,11 - 16,Results for October 6th 2022,IEM Road to Rio 2022 Americas RMR,inf,/matches/2358367/imperial-vs-00nation-iem-road...

In [52]:
# Creating variables to store new kd dataset

smap_players_t1 = []
smap_players_t2 = []
smap_kd_t1 = []
smap_kd_t2 = []

In [53]:
# Creating a function to retrieve kd of each player for one map played

def single_map_kd(ref):
    
    main_page = main_site + ref
    res_page = requests.get(main_page)
    soup_page = bs4.BeautifulSoup(res_page.text,'lxml')

    # 1st map

    smap_players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30].find('span', {'player-nick'}).text)
    smap_players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[31].find('span', {'player-nick'}).text)
    smap_players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[32].find('span', {'player-nick'}).text)
    smap_players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[33].find('span', {'player-nick'}).text)
    smap_players_t1.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[34].find('span', {'player-nick'}).text)

    smap_kd_t1.append(soup_page.find_all('td',{'kd text-center'})[37].text)
    smap_kd_t1.append(soup_page.find_all('td',{'kd text-center'})[38].text)
    smap_kd_t1.append(soup_page.find_all('td',{'kd text-center'})[39].text)
    smap_kd_t1.append(soup_page.find_all('td',{'kd text-center'})[40].text)
    smap_kd_t1.append(soup_page.find_all('td',{'kd text-center'})[41].text)

    smap_players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+15].find('span', {'player-nick'}).text)
    smap_players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+16].find('span', {'player-nick'}).text)
    smap_players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+17].find('span', {'player-nick'}).text)
    smap_players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+18].find('span', {'player-nick'}).text)
    smap_players_t2.append(soup_page.find_all('div',{'gtSmartphone-only statsPlayerName'})[30+19].find('span', {'player-nick'}).text)

    smap_kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+18].text)
    smap_kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+19].text)
    smap_kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+20].text)
    smap_kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+21].text)
    smap_kd_t2.append(soup_page.find_all('td',{'kd text-center'})[37+22].text)

In [54]:
# Retrieving players performance

for i in df_smap['ref']:
    single_map_kd(i)

In [55]:
# Putting together into a DataFrame

d_kd_smap = {'players_t1': smap_players_t1,
        'kd_t1': smap_kd_t1,
        'players_t2': smap_players_t2,
        'kd_t2': smap_kd_t2}

df_smap_players = pd.DataFrame(d_kd_smap)

In [56]:
# Creating a DataFrame draft with the final columns that I want in the final df

df_smap_f = pd.DataFrame(columns = ['team_1', 'team_2', 'score', 'date', 'championship', 'map', 'ref', 'players_t1', 'kd_t1', 'players_t2', 'kd_t2'])

In [57]:
# Final columns for single map dataframe

df_smap_f

Empty DataFrame
Columns: [team_1, team_2, score, date, championship, map, ref, players_t1, kd_t1, players_t2, kd_t2]
Index: []

In [58]:
# Merging Single Maps Results and Player Performance into a single DataFrame

i = 0
j = 0


for i in np.arange(len(df_smap)):
    sub_df_1 = df_smap.iloc[[i]].reset_index(drop=True)
    
    j = i*5
    
    sub_df_2 = df_smap_players.iloc[j:j+5].reset_index(drop=True)
    
    concat = pd.concat([sub_df_1, sub_df_2], axis = 1).fillna(method="ffill", axis=0)
    
    df_smap_f = pd.concat([df_smap_f, concat], axis = 0)

### Dataframe C.Final

In [59]:
# Checking final DataFrame

df_smap_f.head()

,team_1,team_2,score,date,championship,map,ref,players_t1,kd_t1,players_t2,kd_t2
0,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...,decenty,25-10,JOTA,12-16
1,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...,shz,21-12,chelo,16-17
2,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...,kNgV-,18-11,FalleN,15-15
3,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...,piriaz1n,11-16,VINI,11-16
4,Imperial,O PLANO,8 - 16,Results for January 27th 2023,IEM Brazil 2023 South America Open Qualifier 1,vtg,/matches/2361445/o-plano-vs-imperial-iem-brazi...,lub,7-18,boltz,13-18

## Merging Single Map and Bo3 Dataframes

In this part, I merge both dataframes created: df_bo3_f and df_smap_f

#### Cleaning df_bo3_f

In [60]:
df_bo3_f.head()

,team_1,team_2,score,date,championship,map_x,ref,total_matches,score_1,score_2,map_y,indexes,players_t1,kd_t1,players_t2,kd_t2
0,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,chelo,25-12,dumau,8-16
1,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,VINI,21-8,nqz,10-15
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,FalleN,13-5,coldzera,11-19
3,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,JOTA,13-9,TACO,8-18
4,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,bo3,/matches/2361010/imperial-vs-00nation-esl-pro-...,2,16,3,Nuke,2.0,boltz,12-9,latto,6-17

In [61]:
# Renaming column names

df_bo3_f.rename(columns = {'score':'bo3_result', 'map_y':'map'}, inplace = True)

In [62]:
# Dropping columns

df_bo3_f.drop('map_x', axis = 1, inplace = True) # We are interested in the actual map played (column map)
df_bo3_f.drop('total_matches', axis = 1, inplace = True) # No longer need this column
df_bo3_f.drop('indexes', axis = 1, inplace = True) # No longer need this column
df_bo3_f.drop('ref', axis = 1, inplace = True) # No longer need this column

In [63]:
df_bo3_f.head()

,team_1,team_2,bo3_result,date,championship,score_1,score_2,map,players_t1,kd_t1,players_t2,kd_t2
0,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,16,3,Nuke,chelo,25-12,dumau,8-16
1,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,16,3,Nuke,VINI,21-8,nqz,10-15
2,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,16,3,Nuke,FalleN,13-5,coldzera,11-19
3,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,16,3,Nuke,JOTA,13-9,TACO,8-18
4,Imperial,00NATION,2 - 0,Results for January 20th 2023,ESL Pro League Season 17 Conference South America,16,3,Nuke,boltz,12-9,latto,6-17

We would like to maintain the same format as the original database: Imperial score appears first and Opponent score second. We notice that this does happen for team_1 and team_2 columns, but players_t1 and players_t2 this changes. Hence, this part of the code, I'm putting players and their kd's in the same order as team_1 and team_2

#### Cleaning df_smap_f

In [65]:
# Separating score column into 2 more columns, one with first player's score and second with second player's score

df_smap_f['score_1'] = df_smap_f['score'].apply(lambda x:split_score(x)[0])
df_smap_f['score_2'] = df_smap_f['score'].apply(lambda x:split_score(x)[1])

df_smap_f.drop('score', axis = 1, inplace = True) # Removing score column

In [66]:
# Removing other columns

df_smap_f.drop('ref', axis = 1, inplace = True) # No longer needed it

In [67]:
# Creating final database

df_f = pd.concat([df_bo3_f,df_smap_f], axis = 0)

In [68]:
# Reseting index

df_f.reset_index(drop = True,inplace  = True)

In [69]:
# Considering only the players_t1 column

p_t1 = df_f['players_t1'].reset_index(drop=True)

In [70]:
# Adding a new column to track whether the player that appears in the first column (player_t1 in this case) is from Imperial


i = 0
imp_first = []

while i < len(p_t1):
 
    imp_list = p_t1[i:i+5]

    if 'FalleN' in imp_list.values:
        imp_first.extend((1,1,1,1,1))
    else:
        imp_first.extend((0,0,0,0,0))
    
    i += 5
    
df_f['imp_first'] = imp_first

In [71]:
# Creating new adjustments variables to rearrange the order of how player and kd info are displayed.

score_1_adj = []
score_2_adj = []
player_1_adj = []
player_2_adj = []
kd_1_adj = []
kd_2_adj = []

for i in np.arange(len(df_f['imp_first'])):
    if (df_f['imp_first'].iloc[i] == 0) & (pd.isnull(df_f['bo3_result'].iloc[i]) == False):
        score_1_adj.append(df_f['score_2'].iloc[i])
        score_2_adj.append(df_f['score_1'].iloc[i])
        player_1_adj.append(df_f['players_t2'].iloc[i])
        player_2_adj.append(df_f['players_t1'].iloc[i])
        kd_1_adj.append(df_f['kd_t2'].iloc[i])
        kd_2_adj.append(df_f['kd_t1'].iloc[i])
    
    elif (df_f['imp_first'].iloc[i] == 0) & (pd.isnull(df_f['bo3_result'].iloc[i]) == True):
        score_1_adj.append(df_f['score_1'].iloc[i])
        score_2_adj.append(df_f['score_2'].iloc[i])
        player_1_adj.append(df_f['players_t2'].iloc[i])
        player_2_adj.append(df_f['players_t1'].iloc[i])
        kd_1_adj.append(df_f['kd_t2'].iloc[i])
        kd_2_adj.append(df_f['kd_t1'].iloc[i])
    
    else:
        score_1_adj.append(df_f['score_1'].iloc[i])
        score_2_adj.append(df_f['score_2'].iloc[i])
        player_1_adj.append(df_f['players_t1'].iloc[i])
        player_2_adj.append(df_f['players_t2'].iloc[i])
        kd_1_adj.append(df_f['kd_t1'].iloc[i])
        kd_2_adj.append(df_f['kd_t2'].iloc[i])

In [72]:
# Creating new adjusts columns

df_f['score_1_adj'] = score_1_adj
df_f['score_2_adj'] = score_2_adj
df_f['player_1_adj'] = player_1_adj
df_f['player_2_adj'] = player_2_adj
df_f['kd_1_adj'] = kd_1_adj
df_f['kd_2_adj'] = kd_2_adj

In [73]:
# Dropping old columns

df_f.drop(['score_1','score_2','players_t1','kd_t1','players_t2','kd_t2','imp_first'], axis = 1, inplace = True)

In [75]:
# Renaming columns

df_f.rename(columns = {'score_1_adj':'score_1',
                           'score_2_adj':'score_2',
                           'player_1_adj':'players_t1',
                           'player_2_adj':'players_t2',
                           'kd_1_adj':'kd_t1',
                           'kd_2_adj':'kd_t2'}, inplace = True)